// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package fr.sophiacom.wowodc.protobuf;

public final class NotificationProto {
  private NotificationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NotificationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string user = 1;
    /**
     * <code>required string user = 1;</code>
     */
    boolean hasUser();
    /**
     * <code>required string user = 1;</code>
     */
    java.lang.String getUser();
    /**
     * <code>required string user = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserBytes();

    // optional string message = 2;
    /**
     * <code>optional string message = 2;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code Notification}
   */
  public static final class Notification extends
      com.google.protobuf.GeneratedMessage
      implements NotificationOrBuilder {
    // Use Notification.newBuilder() to construct.
    private Notification(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Notification(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Notification defaultInstance;
    public static Notification getDefaultInstance() {
      return defaultInstance;
    }

    public Notification getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Notification(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              user_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              message_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.sophiacom.wowodc.protobuf.NotificationProto.internal_static_Notification_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.sophiacom.wowodc.protobuf.NotificationProto.internal_static_Notification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.class, fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.Builder.class);
    }

    public static com.google.protobuf.Parser<Notification> PARSER =
        new com.google.protobuf.AbstractParser<Notification>() {
      public Notification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Notification(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Notification> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string user = 1;
    public static final int USER_FIELD_NUMBER = 1;
    private java.lang.Object user_;
    /**
     * <code>required string user = 1;</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string user = 1;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          user_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string user = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 2;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      user_ = "";
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Notification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Notification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Notification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Notification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Notification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Notification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Notification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Notification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Notification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Notification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fr.sophiacom.wowodc.protobuf.NotificationProto.Notification prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Notification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements fr.sophiacom.wowodc.protobuf.NotificationProto.NotificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.sophiacom.wowodc.protobuf.NotificationProto.internal_static_Notification_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.sophiacom.wowodc.protobuf.NotificationProto.internal_static_Notification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.class, fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.Builder.class);
      }

      // Construct using fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        user_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.sophiacom.wowodc.protobuf.NotificationProto.internal_static_Notification_descriptor;
      }

      public fr.sophiacom.wowodc.protobuf.NotificationProto.Notification getDefaultInstanceForType() {
        return fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.getDefaultInstance();
      }

      public fr.sophiacom.wowodc.protobuf.NotificationProto.Notification build() {
        fr.sophiacom.wowodc.protobuf.NotificationProto.Notification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fr.sophiacom.wowodc.protobuf.NotificationProto.Notification buildPartial() {
        fr.sophiacom.wowodc.protobuf.NotificationProto.Notification result = new fr.sophiacom.wowodc.protobuf.NotificationProto.Notification(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.user_ = user_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.sophiacom.wowodc.protobuf.NotificationProto.Notification) {
          return mergeFrom((fr.sophiacom.wowodc.protobuf.NotificationProto.Notification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fr.sophiacom.wowodc.protobuf.NotificationProto.Notification other) {
        if (other == fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.getDefaultInstance()) return this;
        if (other.hasUser()) {
          bitField0_ |= 0x00000001;
          user_ = other.user_;
          onChanged();
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000002;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUser()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fr.sophiacom.wowodc.protobuf.NotificationProto.Notification parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fr.sophiacom.wowodc.protobuf.NotificationProto.Notification) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string user = 1;
      private java.lang.Object user_ = "";
      /**
       * <code>required string user = 1;</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string user = 1;</code>
       */
      public java.lang.String getUser() {
        java.lang.Object ref = user_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          user_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string user = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserBytes() {
        java.lang.Object ref = user_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          user_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string user = 1;</code>
       */
      public Builder setUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        user_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string user = 1;</code>
       */
      public Builder clearUser() {
        bitField0_ = (bitField0_ & ~0x00000001);
        user_ = getDefaultInstance().getUser();
        onChanged();
        return this;
      }
      /**
       * <code>required string user = 1;</code>
       */
      public Builder setUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        user_ = value;
        onChanged();
        return this;
      }

      // optional string message = 2;
      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 2;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Notification)
    }

    static {
      defaultInstance = new Notification(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Notification)
  }

  public interface LogOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .Notification notification = 1;
    /**
     * <code>required .Notification notification = 1;</code>
     */
    boolean hasNotification();
    /**
     * <code>required .Notification notification = 1;</code>
     */
    fr.sophiacom.wowodc.protobuf.NotificationProto.Notification getNotification();
    /**
     * <code>required .Notification notification = 1;</code>
     */
    fr.sophiacom.wowodc.protobuf.NotificationProto.NotificationOrBuilder getNotificationOrBuilder();

    // required int32 sendingTime = 2;
    /**
     * <code>required int32 sendingTime = 2;</code>
     */
    boolean hasSendingTime();
    /**
     * <code>required int32 sendingTime = 2;</code>
     */
    int getSendingTime();
  }
  /**
   * Protobuf type {@code Log}
   */
  public static final class Log extends
      com.google.protobuf.GeneratedMessage
      implements LogOrBuilder {
    // Use Log.newBuilder() to construct.
    private Log(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Log(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Log defaultInstance;
    public static Log getDefaultInstance() {
      return defaultInstance;
    }

    public Log getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Log(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = notification_.toBuilder();
              }
              notification_ = input.readMessage(fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(notification_);
                notification_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sendingTime_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.sophiacom.wowodc.protobuf.NotificationProto.internal_static_Log_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.sophiacom.wowodc.protobuf.NotificationProto.internal_static_Log_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.sophiacom.wowodc.protobuf.NotificationProto.Log.class, fr.sophiacom.wowodc.protobuf.NotificationProto.Log.Builder.class);
    }

    public static com.google.protobuf.Parser<Log> PARSER =
        new com.google.protobuf.AbstractParser<Log>() {
      public Log parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Log(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Log> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .Notification notification = 1;
    public static final int NOTIFICATION_FIELD_NUMBER = 1;
    private fr.sophiacom.wowodc.protobuf.NotificationProto.Notification notification_;
    /**
     * <code>required .Notification notification = 1;</code>
     */
    public boolean hasNotification() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Notification notification = 1;</code>
     */
    public fr.sophiacom.wowodc.protobuf.NotificationProto.Notification getNotification() {
      return notification_;
    }
    /**
     * <code>required .Notification notification = 1;</code>
     */
    public fr.sophiacom.wowodc.protobuf.NotificationProto.NotificationOrBuilder getNotificationOrBuilder() {
      return notification_;
    }

    // required int32 sendingTime = 2;
    public static final int SENDINGTIME_FIELD_NUMBER = 2;
    private int sendingTime_;
    /**
     * <code>required int32 sendingTime = 2;</code>
     */
    public boolean hasSendingTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 sendingTime = 2;</code>
     */
    public int getSendingTime() {
      return sendingTime_;
    }

    private void initFields() {
      notification_ = fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.getDefaultInstance();
      sendingTime_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNotification()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSendingTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getNotification().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, notification_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, sendingTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, notification_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sendingTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Log parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Log parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Log parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Log parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Log parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Log parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Log parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Log parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Log parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.sophiacom.wowodc.protobuf.NotificationProto.Log parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fr.sophiacom.wowodc.protobuf.NotificationProto.Log prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Log}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements fr.sophiacom.wowodc.protobuf.NotificationProto.LogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.sophiacom.wowodc.protobuf.NotificationProto.internal_static_Log_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.sophiacom.wowodc.protobuf.NotificationProto.internal_static_Log_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.sophiacom.wowodc.protobuf.NotificationProto.Log.class, fr.sophiacom.wowodc.protobuf.NotificationProto.Log.Builder.class);
      }

      // Construct using fr.sophiacom.wowodc.protobuf.NotificationProto.Log.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNotificationFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (notificationBuilder_ == null) {
          notification_ = fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.getDefaultInstance();
        } else {
          notificationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        sendingTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.sophiacom.wowodc.protobuf.NotificationProto.internal_static_Log_descriptor;
      }

      public fr.sophiacom.wowodc.protobuf.NotificationProto.Log getDefaultInstanceForType() {
        return fr.sophiacom.wowodc.protobuf.NotificationProto.Log.getDefaultInstance();
      }

      public fr.sophiacom.wowodc.protobuf.NotificationProto.Log build() {
        fr.sophiacom.wowodc.protobuf.NotificationProto.Log result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fr.sophiacom.wowodc.protobuf.NotificationProto.Log buildPartial() {
        fr.sophiacom.wowodc.protobuf.NotificationProto.Log result = new fr.sophiacom.wowodc.protobuf.NotificationProto.Log(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (notificationBuilder_ == null) {
          result.notification_ = notification_;
        } else {
          result.notification_ = notificationBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sendingTime_ = sendingTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.sophiacom.wowodc.protobuf.NotificationProto.Log) {
          return mergeFrom((fr.sophiacom.wowodc.protobuf.NotificationProto.Log)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fr.sophiacom.wowodc.protobuf.NotificationProto.Log other) {
        if (other == fr.sophiacom.wowodc.protobuf.NotificationProto.Log.getDefaultInstance()) return this;
        if (other.hasNotification()) {
          mergeNotification(other.getNotification());
        }
        if (other.hasSendingTime()) {
          setSendingTime(other.getSendingTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNotification()) {
          
          return false;
        }
        if (!hasSendingTime()) {
          
          return false;
        }
        if (!getNotification().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fr.sophiacom.wowodc.protobuf.NotificationProto.Log parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fr.sophiacom.wowodc.protobuf.NotificationProto.Log) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .Notification notification = 1;
      private fr.sophiacom.wowodc.protobuf.NotificationProto.Notification notification_ = fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          fr.sophiacom.wowodc.protobuf.NotificationProto.Notification, fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.Builder, fr.sophiacom.wowodc.protobuf.NotificationProto.NotificationOrBuilder> notificationBuilder_;
      /**
       * <code>required .Notification notification = 1;</code>
       */
      public boolean hasNotification() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Notification notification = 1;</code>
       */
      public fr.sophiacom.wowodc.protobuf.NotificationProto.Notification getNotification() {
        if (notificationBuilder_ == null) {
          return notification_;
        } else {
          return notificationBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Notification notification = 1;</code>
       */
      public Builder setNotification(fr.sophiacom.wowodc.protobuf.NotificationProto.Notification value) {
        if (notificationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          notification_ = value;
          onChanged();
        } else {
          notificationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Notification notification = 1;</code>
       */
      public Builder setNotification(
          fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.Builder builderForValue) {
        if (notificationBuilder_ == null) {
          notification_ = builderForValue.build();
          onChanged();
        } else {
          notificationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Notification notification = 1;</code>
       */
      public Builder mergeNotification(fr.sophiacom.wowodc.protobuf.NotificationProto.Notification value) {
        if (notificationBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              notification_ != fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.getDefaultInstance()) {
            notification_ =
              fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.newBuilder(notification_).mergeFrom(value).buildPartial();
          } else {
            notification_ = value;
          }
          onChanged();
        } else {
          notificationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Notification notification = 1;</code>
       */
      public Builder clearNotification() {
        if (notificationBuilder_ == null) {
          notification_ = fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.getDefaultInstance();
          onChanged();
        } else {
          notificationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .Notification notification = 1;</code>
       */
      public fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.Builder getNotificationBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getNotificationFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Notification notification = 1;</code>
       */
      public fr.sophiacom.wowodc.protobuf.NotificationProto.NotificationOrBuilder getNotificationOrBuilder() {
        if (notificationBuilder_ != null) {
          return notificationBuilder_.getMessageOrBuilder();
        } else {
          return notification_;
        }
      }
      /**
       * <code>required .Notification notification = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          fr.sophiacom.wowodc.protobuf.NotificationProto.Notification, fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.Builder, fr.sophiacom.wowodc.protobuf.NotificationProto.NotificationOrBuilder> 
          getNotificationFieldBuilder() {
        if (notificationBuilder_ == null) {
          notificationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              fr.sophiacom.wowodc.protobuf.NotificationProto.Notification, fr.sophiacom.wowodc.protobuf.NotificationProto.Notification.Builder, fr.sophiacom.wowodc.protobuf.NotificationProto.NotificationOrBuilder>(
                  notification_,
                  getParentForChildren(),
                  isClean());
          notification_ = null;
        }
        return notificationBuilder_;
      }

      // required int32 sendingTime = 2;
      private int sendingTime_ ;
      /**
       * <code>required int32 sendingTime = 2;</code>
       */
      public boolean hasSendingTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 sendingTime = 2;</code>
       */
      public int getSendingTime() {
        return sendingTime_;
      }
      /**
       * <code>required int32 sendingTime = 2;</code>
       */
      public Builder setSendingTime(int value) {
        bitField0_ |= 0x00000002;
        sendingTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sendingTime = 2;</code>
       */
      public Builder clearSendingTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sendingTime_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Log)
    }

    static {
      defaultInstance = new Log(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Log)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Notification_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Notification_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Log_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Log_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022notification.proto\"-\n\014Notification\022\014\n\004" +
      "user\030\001 \002(\t\022\017\n\007message\030\002 \001(\t\"?\n\003Log\022#\n\014no" +
      "tification\030\001 \002(\0132\r.Notification\022\023\n\013sendi" +
      "ngTime\030\002 \002(\005B1\n\034fr.sophiacom.wowodc.prot" +
      "obufB\021NotificationProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Notification_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Notification_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Notification_descriptor,
              new java.lang.String[] { "User", "Message", });
          internal_static_Log_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Log_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Log_descriptor,
              new java.lang.String[] { "Notification", "SendingTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
